### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by luka2g** [PMF-ZNMZR/pyREMAKEmsh#3]
Have satisfied the install requrements 

LSW, Ubuntu 20.01

When executing 

>>> tolerance = 1e-4
>>> input_data = 'InputData/GeometryData1.json'
>>> input_dictionary = SaveJsonToDict(input_data)
>>> pyREMAKEmsh.pyREMAKEmsh(input_dictionary, tolerance)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/luka/pyREMAKEmsh/pyREMAKEmsh.py", line 42, in __init__
    self.MakeDict()
  File "/home/luka/pyREMAKEmsh/pyREMAKEmsh.py", line 1109, in MakeDict
    self.ConstructGeometry()
  File "/home/luka/pyREMAKEmsh/pyREMAKEmsh.py", line 922, in ConstructGeometry
    geom.boolean_fragments(surface, self.Points_done_not_on_any_entity[i], delete_first = True, delete_other = True)
TypeError: boolean_fragments() got an unexpected keyword argument 'delete_first'

**Comment by luka2g** [comment]
luka@pc-luka:~/pyREMAKEmsh$ sudo pip3 install pygmsh --upgrade
[sudo] password for luka:
Collecting pygmsh
  Downloading pygmsh-7.1.12-py3-none-any.whl (44 kB)
     |████████████████████████████████| 44 kB 907 kB/s
Collecting meshio<6,>=4.3.2
  Downloading meshio-5.0.2-py3-none-any.whl (163 kB)
     |████████████████████████████████| 163 kB 2.9 MB/s
Collecting numpy>=1.9
  Downloading numpy-1.21.2-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (15.8 MB)
     |████████████████████████████████| 15.8 MB 8.9 MB/s
Installing collected packages: numpy, meshio, pygmsh
Successfully installed meshio-5.0.2 numpy-1.21.2 pygmsh-7.1.12
luka@pc-luka:~/pyREMAKEmsh$ sudo pip3 install gmsh --upgrade
Collecting gmsh
  Downloading gmsh-4.8.4.tar.gz (10 kB)
Building wheels for collected packages: gmsh
  Building wheel for gmsh (setup.py) ... done
  Created wheel for gmsh: filename=gmsh-4.8.4-py3-none-any.whl size=112702987 sha256=7538684377149466991afc9378e40fb9aaeddaad26c2b10925bc42ec492b4f41
  Stored in directory: /root/.cache/pip/wheels/01/5a/f1/47592a576f656dde945a8412d0c2dd0a1d62b10629534dad94
Successfully built gmsh
Installing collected packages: gmsh
Successfully installed gmsh-4.8.4
luka@pc-luka:~/pyREMAKEmsh$ python3
Python 3.8.10 (default, Sep 28 2021, 16:10:42)
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyREMAKEmsh
>>> import json
>>> def SaveJsonToDict(json_file):
...     with open(json_file) as f:
...             input_dictionary = json.load(f)
...     return input_dictionary
...
>>> tolerance = 1e-4
>>> input_data = 'InputData/GeometryData1.json'
>>> input_dictionary = SaveJsonToDict(input_data)
>>> pyREMAKEmsh.pyREMAKEmsh(input_dictionary, tolerance)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/luka/pyREMAKEmsh/pyREMAKEmsh.py", line 42, in __init__
    self.MakeDict()
  File "/home/luka/pyREMAKEmsh/pyREMAKEmsh.py", line 1109, in MakeDict
    self.ConstructGeometry()
  File "/home/luka/pyREMAKEmsh/pyREMAKEmsh.py", line 922, in ConstructGeometry
    geom.boolean_fragments(surface, self.Points_done_not_on_any_entity[i], delete_first = True, delete_other = True)
TypeError: boolean_fragments() got an unexpected keyword argument 'delete_first'

**Comment by domagojlacmanovic** [comment]
That is really weird because the error is: 

TypeError: boolean_fragments() got an unexpected keyword argument 'delete_first',

but from the pygmsh source code, definition of method boolean_fragments is:

def boolean_fragments( self, d0, d1, delete_first: bool = True, delete_other: bool = True).

I don't know what is the problem but you can try executing it with python, not python3, but I don't think it will make a difference. 

Even though the problem is in pygmsh you can try:

pip3 install gmsh-sdk

It is probably a version thing but I can't figure out is the problem.

Let me know if this helps, I will try to figure out what else might be causing this. 

PS. Everything works fine on my computer.
