### ISSUE TITLE
Mesh quality of the benchmark models

### ISSUE THREAD

**Issue by luka2g** [PMF-ZNMZR/pyREMAKEmsh#4]
The quality of the benchmark models is different than in the paper. It seems that the virtual stiffener algorithm had messed up the meshing on the upper adjacent plate.

**Comment by luka2g** [comment]
![image](https://user-images.githubusercontent.com/51400376/137642074-9a1e2f68-e608-438f-a511-5e4660bfdfa6.png)

**Comment by luka2g** [comment]
![image](https://user-images.githubusercontent.com/51400376/137642152-efe6c74d-ed65-47a0-87fe-59228b1007c9.png)

**Comment by domagojlacmanovic** [comment]
Problem fixed. It was meshing with wrong algorithm. It should be good now.
